name: recalpp
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - libffi=3.4.2
  - openssl=1.1.1t
  - pip=22.3.1
  - pymongo=3.12.0
  - python=3.10.9
  - pyyaml=6.0
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - tzdata=2022g
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - wincertstore=0.2
  - xz=5.2.10
  - yaml=0.2.5
  - zlib=1.2.13