name: recalpp
channels:
- defaults
- conda-forge
dependencies:
- dnspython=2.2.1
- python-dotenv=1.0.0
- pip=22.3.1
- pyyaml=6.0
- pymongo=3.12.0
- django=4.1
- requests=2.28.1
- black=22.6.0
- gunicorn-20.1.0