# Generated by Django 4.1.8 on 2023-04-22 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("class_number", models.CharField(max_length=255)),
                ("section", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("pu_calc_status", models.CharField(max_length=255)),
                ("seat_status", models.CharField(max_length=255)),
                ("type_name", models.CharField(max_length=255)),
                ("capacity", models.IntegerField()),
                ("enrollment", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.CharField(max_length=255)),
                ("course_id", models.CharField(max_length=255)),
                ("catalog_number", models.CharField(max_length=255)),
                ("title", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("track", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("seat_reservations", models.CharField(max_length=255)),
                ("term_code", models.CharField(max_length=255)),
                ("term_name", models.CharField(max_length=255)),
                ("subject_code", models.CharField(max_length=255)),
                ("crosslistings_string", models.TextField()),
                ("distribution_areas", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("emplid", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("meeting_number", models.IntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("days", models.CharField(max_length=255)),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="meetings", to="data_ingestion.class"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrossListing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=255)),
                ("catalog_number", models.CharField(max_length=255)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_ingestion.course")),
            ],
        ),
        migrations.CreateModel(
            name="CourseInstructor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_ingestion.course")),
                (
                    "instructor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_ingestion.instructor"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="course",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_ingestion.course"),
        ),
    ]
