# Generated by Django 4.1.8 on 2023-04-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_ingestion", "0002_remove_course_crosslistings_string_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="emplid",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
