# Generated by Django 4.1.8 on 2023-04-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_ingestion", "0003_alter_instructor_emplid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="guid",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
