# Generated by Django 4.1.8 on 2023-04-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_ingestion", "0004_alter_course_guid"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="crosslistings_string",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="distribution_areas",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
