# Generated by Django 4.1.8 on 2023-04-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_ingestion", "0006_alter_course_crosslistings_string_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="crosslistings_string",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="distribution_areas",
            field=models.CharField(max_length=255),
        ),
    ]
