# Generated by Django 4.1.8 on 2023-05-08 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_ingestion", "0007_alter_course_crosslistings_string_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=3)),
                ("degree", models.CharField(choices=[("AB", "AB"), ("BSE", "BSE")], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="RequiredCourse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_ingestion.course")),
                ("major", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_ingestion.major")),
            ],
        ),
    ]
