# Generated by Django 4.1.8 on 2023-05-08 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_ingestion", "0008_major_requiredcourse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="major",
            name="code",
        ),
        migrations.RemoveField(
            model_name="major",
            name="degree",
        ),
    ]
